### ISSUE TITLE
Error :config.cfg: No such file

### ISSUE THREAD

**Issue by hechenwei** [rrs-oacis/rrs-oacis#3]
Environment information:
OS Platform and Distribution: Linux Ubuntu 16.04;
Running RRS-OACIS in docker with one computer;

Describe the problem:
I have operated RRS-OACIS on the order of the tutorial written in the doc and selected localhost(default) as the host running the simulator(agent_test,map_test).
The status of the simulator went through with submitted running and failed.

Error message:
simulator return code: 253

Output Files:
(The following is the issue outputed in _stderr.txt)
./killjava.sh: line 3: /home/oacis/oacis/public/Result_development/work/__work__/config.cfg: No such file or directory
./setup_MT.sh: line 3: /home/oacis/oacis/public/Result_development/work/__work__/config.cfg: No such file or directory
ssh: Could not resolve hostname s: Name or service not known
ssh: Could not resolve hostname s: Name or service not known
ssh: Could not resolve hostname s: Name or service not known
lost connection
ssh: Could not resolve hostname s: Name or service not known
ssh: Could not resolve hostname s: Name or service not known
ssh: Could not resolve hostname f: Name or service not known
ssh: Could not resolve hostname f: Name or service not known
ssh: Could not resolve hostname f: Name or service not known
lost connection
ssh: Could not resolve hostname f: Name or service not known
ssh: Could not resolve hostname f: Name or service not known
ssh: Could not resolve hostname p: Name or service not known
ssh: Could not resolve hostname p: Name or service not known
ssh: Could not resolve hostname p: Name or service not known
lost connection
ssh: Could not resolve hostname p: Name or service not known
ssh: Could not resolve hostname p: Name or service not known
ssh: Could not resolve hostname a: Name or service not known
ssh: Could not resolve hostname a: Name or service not known
ssh: Could not resolve hostname a: Name or service not known
lost connection
ssh: Could not resolve hostname a: Name or service not known
ssh: Could not resolve hostname a: Name or service not known

BTW it's a good idea to apply oacis as an analysing tool of RRS.

**Comment by tkmnet** [comment]
Thank you for your reporting.
I fixed the phase of starting the run.

Would you pull the image again and try it.

**Comment by hechenwei** [comment]
Thanks a lot for your responding.
There stil are some issues .

The ERROR message has changed:
 simulator return code: 2

The Output Files(_stderr.txt) has changed:
Use of uninitialized value $host in substitution (s///) at /home/oacis/rrs-oacis/rrsenv/script/rrscluster line 356.
mandatory host argument missing at /home/oacis/rrs-oacis/rrsenv/script/rrscluster line 357.

There is a condition should be noticed is that the map uploading takes a long time and it isn't generated below MAP tag.

**Comment by tkmnet** [comment]
@hechenwei 
I want to check your cluster settings.
Could you upload a screenshot of the clusters settings page?

**Comment by tkmnet** [comment]
You can use following storage to upload.
https://www.dropbox.com/request/2flSwPBY3Pv2zTgT1P4R

Thank you.

**Comment by hechenwei** [comment]
Sorry,I may misunderstand the project.
I thought if there were only one computer to run RRSOACIS it would be ok to use the localhost as the host to run the simulators.And I didn't set any cluster.

**Comment by tkmnet** [comment]
Sorry at the lack of explanation. Even if only one computer is used, registration as a cluster is necessary. In that case, specify the Docker's host IP etc. to cluster’s hosts.

**Comment by tkmnet** [comment]
Currentry rrs-oacis is not support to run simulation in self container. Thus, you cannot specify "localhost". you must specify Docker host's IP(like 172.17.0.1).

**Comment by tkmnet** [comment]
(I will consider to support using self container to run simulation as future plan.)

**Comment by tkmnet** [comment]
#### How to get your Docker host's IP address

`> docker exec rrsoacis ip a`
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>        valid_lft forever preferred_lft forever
> 7: eth0@if8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
>     link/ether 02:42:ac:11:00:03 brd ff:ff:ff:ff:ff:ff link-netnsid 0
>     inet 172.17.0.3/16 brd 172.17.255.255 scope global eth0
>        valid_lft forever preferred_lft forever

You can see Docker container's IP(172.17.0.3).
In this case, maybe your Docker host's IP is "172.17.0.1". (please, replase last byte to 1.)

**Comment by tkmnet** [comment]
Plaese permit to access to X11 server useing following command.
`xhost +`

**Comment by tkmnet** [comment]
I am sorry. currentry RRS is not support OpenJDK. Please use Oracle JDK.
.

**Comment by hechenwei** [comment]
It's very kind of you to answer my questions.(Some of them are primary)
